export const PERFILES_BUSCADOS = [
  'TECNOLOGIA_AGROPECUARIA',
  'ADMINISTRACION_EMPRESAS_AGROPECUARIAS',
  'INGENIERO_AGROPECUARIO',
] as const;

export const MODALIDADES_CONTRATACION = [
  'CONTRATO_SENA',
  'CONVENIO',
  'VOLUNTARIA',
] as const;
